### PR TITLE
Branch fix paid policy to json

### LINKED ISSUE #102: Fix Paid policies to json bug
Fix Paid policies to json bug

### PR DESCRIPTION
**Pull request by SSirMentos**
Branch fix paid policy to json
close #102

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Payment.java [hunk 1]
```diff
@@ -36,16 +40,27 @@ public Payment(String insurancePayment) {
         requireNonNull(insurancePayment);
         checkArgument(isValidInsurancePayment(insurancePayment), MESSAGE_CONSTRAINTS);
         value = insurancePayment;
-        String[] parts = insurancePayment.trim().split("\\s+");
-        paymentDueDate = LocalDate.parse(parts[0], DATE_FORMATTER);
-        amount = new BigDecimal(parts[1]);
+        if (value.equals(FULLY_PAID_PAYMENT)) {
```
Comment (Edwin1022) [inline src/main/java/seedu/address/model/person/Payment.java:43]: I like how you abstract out the FULLY_PAID_PAYMENT final string

File: src/main/java/seedu/address/model/person/Policy.java [hunk 2]
```diff
@@ -3,34 +3,43 @@
...
     public static final String MESSAGE_CONSTRAINTS = "Policy details should be in the format 'policyName startDate "
             + "endDate' paydate amountDue, where dates are in 'yyyy-MM-dd' format.";
 
+    //private static final String FULLY_PAID = "Fully Paid";
+
     private static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd");
-    private static final String TOSTRINGFORMATTER = "([\\w\\s]+)\\s+\\((\\d{4}-\\d{2}-\\d{2})\\s*"
-            + "to\\s*(\\d{4}-\\d{2}-\\d{2})\\)\\s*\\$([0-9.]+)\\s*due\\s*on\\s*(\\d{4}-\\d{2}-\\d{2})";
 
+    private static final String TOSTRINGFORMATTER = "([\\w\\s]+)\\s+\\((\\d{4}-\\d{2}-\\d{2})\\s*"
```
Comment (Edwin1022) [inline src/main/java/seedu/address/model/person/Policy.java:27]: Good job!!!

File: src/main/java/seedu/address/model/person/Policy.java [hunk 3]
```diff
@@ -153,33 +165,32 @@ public static Comparator<Policy> getPolicyPaymentDueDateComparator() {
...
-            policyDetails.add(policyName);
-            policyDetails.add(startDate);
-            policyDetails.add(endDate);
-            policyDetails.add(paymentAmount);
-            policyDetails.add(paymentDate);
+            policyDetails.put(POLICY_NAME, matcher.group(1));
+            policyDetails.put(START_DATE, matcher.group(2));
+            policyDetails.put(END_DATE, matcher.group(3));
+            if (matcher.group(4) != null && matcher.group(5) != null) {
+                // Handle the case when there is an amount due
```
Comment (Edwin1022) [inline src/main/java/seedu/address/model/person/Policy.java:182]: I like how you include comments in this part so that it makes your code looks much clearer

File: src/main/java/seedu/address/model/person/Policy.java [hunk 4]
```diff
@@ -3,34 +3,43 @@
...
+
     private static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd");
-    private static final String TOSTRINGFORMATTER = "([\\w\\s]+)\\s+\\((\\d{4}-\\d{2}-\\d{2})\\s*"
-            + "to\\s*(\\d{4}-\\d{2}-\\d{2})\\)\\s*\\$([0-9.]+)\\s*due\\s*on\\s*(\\d{4}-\\d{2}-\\d{2})";
 
+    private static final String TOSTRINGFORMATTER = "([\\w\\s]+)\\s+\\((\\d{4}-\\d{2}-\\d{2})\\s*"
+            + "to\\s*(\\d{4}-\\d{2}-\\d{2})\\)\\s*"
+           + "(?:\\$([0-9.]+)\\s*due\\s*on\\s*(\\d{4}-\\d{2}-\\d{2})|(?<paid>Fully Paid))";
 
+    private static final String POLICY_NAME = "policyName"; // Policy name
```
Comment (Edwin1022) [inline src/main/java/seedu/address/model/person/Policy.java:31]: Looks good to me!!

File: src/main/java/seedu/address/model/person/Payment.java [hunk 5]
```diff
@@ -21,8 +21,12 @@ public class Payment {
      */
     public static final String VALIDATION_REGEX = "\\d{4}-\\d{2}-\\d{2} \\d+(\\.\\d{1,2})?";
 
+
+
     private static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd");
 
+    private static final String FULLY_PAID_PAYMENT = BigDecimal.ZERO.toString() + " " + LocalDate.MAX.toString();
```
Comment (Edwin1022) [inline src/main/java/seedu/address/model/person/Payment.java:28]: Nice work!!

**Review by Edwin1022 — COMMENTED** [review]
Lgtm
