### PR TITLE
Fix Policy Format Bug

### LINKED ISSUE #97: Fix Policy Json Bug
Fixed bug where if there is a space in the policy field when assigning to a person, only the second word will be reflected when program was ran again

### PR DESCRIPTION
**Pull request by SSirMentos**
Fix Policy Format Bug
close #97

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/AddCommand.java [hunk 1]
```diff
@@ -28,15 +27,15 @@ public class AddCommand extends Command {
...
-            + PREFIX_BIRTHDAY + "1990-10-10"
-            + PREFIX_APPOINTMENT + "2024-12-12 12:00"
-            + PREFIX_TAG + "Accident";
+            + PREFIX_BIRTHDAY + "BIRTHDAY "
+            + PREFIX_APPOINTMENT + "APPOINTMENT "
+            + "\nExample: " + COMMAND_WORD + " "
+            + PREFIX_NAME + "John Doe" + " "
+            + PREFIX_PHONE + "98765432" + " "
+            + PREFIX_EMAIL + "johnd@example.com" + " "
+            + PREFIX_ADDRESS + "311, Clementi Ave 2, #02-25" + " "
```
Comment (The0nlyJuan) [inline src/main/java/seedu/address/logic/commands/AddCommand.java:36]: Good Fix! Finally the example works!

File: src/main/java/seedu/address/logic/parser/AssignPolicyCommandParser.java [hunk 2]
```diff
@@ -43,9 +43,12 @@ public AssignPolicyCommand parse(String args) throws ParseException {
...
                 PREFIX_POLICY_END_DATE, PREFIX_NEXT_PAYMENT_DATE,
                 PREFIX_PAYMENT_AMOUNT);
-
-        Policy policy = ParserUtil.parsePolicy(args);
-        return new AssignPolicyCommand(index, policy);
+        try {
+            Policy policy = ParserUtil.parsePolicy(args);
+            return new AssignPolicyCommand(index, policy);
+        } catch (ParseException pe) {
+            throw new ParseException(pe.getMessage() + "\n" + AssignPolicyCommand.MESSAGE_USAGE);
```
Comment (The0nlyJuan) [inline src/main/java/seedu/address/logic/parser/AssignPolicyCommandParser.java:50]: good defensive programming usage

**Comment by M-kew** [comment]
LGTM.
