### PR TITLE
Fix edit command allowing duplicate policy names

### LINKED ISSUE #79: Fix edit command allowing duplicate policy names
Fix edit command allowing duplicate policy name

### PR DESCRIPTION
**Pull request by MingYiAw**
The edit command fails to correctly identify duplicate policy names, allowing policies tho share the same name using edit command.

Handling the duplication of policy name in edit command prevents possible error cause by having multiple policies with same name.

Let's implements a check to ensure that duplicate policy names are detected properly and display an error to inform the user.

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -141,17 +141,49 @@ public static List<Policy> editPolicies(Person personToEdit, Map<Index, Policy>
...
 
-            if (index.getZeroBased() >= policiesSize) {
+            if (zeroBasedIndex >= policiesSize) {
                 throw new CommandException(Messages.MESSAGE_INVALID_POLICY_DISPLAYED_INDEX);
             }
 
-            updatedPolicies.set(index.getZeroBased(), policy);
+            int duplicatePolicyIndex = getDuplicatePolicyIndex(policy, updatedPolicies);
+            boolean isPolicyToEdit = (duplicatePolicyIndex == zeroBasedIndex);
+            boolean isNotDuplicatePolicy = (duplicatePolicyIndex == -1);
```
Comment (M-kew) [inline src/main/java/seedu/address/logic/commands/EditCommand.java:152]: Possible if can add a comment to explain what the "-1" represent or use a constant variable to represent the -1. Just some suggestion. But this works too

**Comment by M-kew** [comment]
LGTM.
